In [17]:
#Data Input Pipeline
import numpy as np
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [19]:
x_train_flat = x_train.reshape(x_train.shape[0],-1).T
x_test_flat = x_test.reshape(x_test.shape[0],-1).T


In [40]:
print(x_train_flat.shape)

(784, 60000)


In [21]:
y_train_onehot = np.eye(10)[y_train]
y_test_onehot = np.eye(10)[y_test]

In [26]:
nH = [50]
m_train = 60000

In [27]:
print(y_train_onehot)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [28]:
print(x_train_flat.shape)

(784, 60000)


In [43]:
W1 = np.random.randn(nH[0], x_train_flat.shape[0]).T
b1 = np.random.randn(1,nH[0])
Z1 = np.dot(x_train_flat.T, W1) + b1
labels_mat = np.random.randn(x_train.shape[0])

In [ ]:
#Addd bias

In [ ]:
#appply thresholding funcb

In [ ]:
#brepeat for layer 2

In [ ]:
#